### PR TITLE
Logo change

### LINKED ISSUE #49: Permitir o texto de lei em Markdown

### PR DESCRIPTION
**Pull request by erickzanardo**
This PR closes #58 and #51 by updating the site logo

### How was it before?

- the site was still using the old version of the logo

### What has changed?

- the logo image
- added the `gem` `mailcatcher` to help testing emails
- removed unused logo images from the project, to avoid confusion in the future

### What should I pay attention when reviewing this PR?

Nothing special.

### Is this PR dangerous?

No.

### CODE REVIEW

**Comment by guimello** [comment]
@erickzanardo The base branch must be *development*. And I think there was some copy-paste there on the PR message.

**Comment by erickzanardo** [comment]
@guimello right, I've changed the base branch to the correct one, thanks.

**Comment by guimello** [comment]
🚀  ship it

**Comment by marcoamarelo** [comment]
Excellent! PR accept. Ship it :-)

**Pull request merged**
